# Build settings
highlighter: pygments
gems:
  - jemoji

# Site settings
title: "Michael Bellistri"
description: > # this means to ignore newlines until "email:"
   Computer Science B.S, University of Maryland

email: m.g.bellistri@gmail.com
#blog logo
logo: "/assets/images/mb_icon.jpg"
# blog cover
cover: "/assets/images/background_image.jpg"

name: 'Michael Bellistri'
author: 'Michael Bellistri'
author_image: "/assets/images/professional_image.jpg"

paginate:	5

url: "http://mikebellistri.github.io" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@mikebellistri'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

# social icons and sharing options
social:
#  - icon:	twitter
#    url:	https://twitter.com/mikebellistri
#    desc: Follow me on twitter
#    share_url: http://twitter.com/share
#    share_title: ?text=
#    share_link: "&amp;url="

  - icon:	linkedin
    url:	https://www.linkedin.com/pub/michael-billestri/48/410/a45
    desc: Connect with me linkedin
    share_url: 
    share_title:
    share_link:

  - icon:	github
    url:	https://github.com/mikebellistri
    desc:	Portfolio
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
